---
name: "Test"
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md

permissions: {}

jobs:
  darwin-dev-test:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test build script for darwin-amd64
        run: |
          rm -rf ${GITHUB_WORKSPACE}/build
          make dev-test
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

  linux-dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test build script for linux-amd64
        run: |
          rm -rf ${GITHUB_WORKSPACE}/build
          make dev-test
